name: xact3d
favicon: null
layout_spectrum: 0.06778299808502197
typography_spectrum: 0.31875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
